#!/usr/bin/env python3
"""Generate web/config.js from stack outputs, upload the client, invalidate CloudFront."""
import json
import mimetypes
import sys
from pathlib import Path

import boto3

ROOT = Path(__file__).resolve().parent.parent
REGION = "us-east-1"

s3 = boto3.client("s3", region_name=REGION)
cf = boto3.client("cloudfront")


def main():
    out = json.loads((ROOT / ".deploy" / "outputs.json").read_text())["EnterpriseAdvisor"]

    config = (
        "// generated by scripts/deploy_web.py — do not edit\n"
        "const CONFIG = " + json.dumps({
            "region": REGION,
            "apiEndpoint": out["ApiEndpoint"],
            "userPoolId": out["UserPoolId"],
            "userPoolClientId": out["UserPoolClientId"],
        }, indent=2) + ";\n"
    )
    (ROOT / "web" / "config.js").write_text(config)
    print("wrote web/config.js")

    bucket = out["SiteBucket"]
    web = ROOT / "web"
    for path in sorted(web.rglob("*")):
        if not path.is_file():
            continue
        object_key = path.relative_to(web).as_posix()
        ctype = mimetypes.guess_type(path.name)[0] or "application/octet-stream"
        s3.put_object(Bucket=bucket, Key=object_key, Body=path.read_bytes(),
                      ContentType=ctype, CacheControl="no-cache")
        print(f"  uploaded {object_key:22s} {ctype}")

    site = out["SiteUrl"]
    dist_domain = site.replace("https://", "")
    for d in cf.list_distributions().get("DistributionList", {}).get("Items", []):
        if d["DomainName"] == dist_domain:
            cf.create_invalidation(
                DistributionId=d["Id"],
                InvalidationBatch={
                    "Paths": {"Quantity": 1, "Items": ["/*"]},
                    "CallerReference": str(__import__("time").time()),
                },
            )
            print(f"invalidated {d['Id']}")
            break

    print(f"\n{site}")


if __name__ == "__main__":
    main()
